#!/bin/sh
set -e
set -x

usage() {
    echo "ubuild-check-tag [--config-file=<config>] <configuration> <git directory> <tag>"
    echo
    echo "If check is succesful, emits the list of uids for the signature key"
}

case "$1" in
    --config-file=*)
        CONFIG_FILE=${1#--config-file=}
        shift;;
    *)
        break;;
esac

CONFIGURATION="$1"
GIT_DIR="$2"
TAG=$(echo "$3" | sed -e 's/:/+/g')

if [ $# -ne 3 ]; then
    usage
    exit 1
fi

if [ -n "$CONFIG_FILE" ]; then
    . $CONFIG_FILE
else
    [ -f ~/.ubuild.conf ] && . ~/.ubuild.conf && PATH=$(pwd):$PATH || . /etc/ubuild/ubuild.conf
fi

TMPDIR=$(mktemp -d)
cleanup() {
    RET=$?
    rm -rf "$TMPDIR"
    return $RET
}
trap cleanup 0 QUIT TERM

(cd "$GIT_DIR"; git cat-file tag "refs/tags/$TAG" > "$TMPDIR/tag")

sed -e '/-----BEGIN PGP SIGNATURE-----/Q' < "$TMPDIR/tag" > "$TMPDIR/contents"
sed -ne '/-----BEGIN PGP SIGNATURE-----/,$p' < "$TMPDIR/tag" > "$TMPDIR/contents.asc"

if ! OUT=$(gpgv --keyring "$GIT_KEYRING" "$TMPDIR/contents.asc" 2>&1); then
    printf '%s\n' "$OUT" >&2
    exit 1
fi

printf %s "$OUT" | sed '/^gpgv: \(Good signature from\|.*aka\) "\(.*\)"/!d;s//\2/'
